template: external-bridged-provider
provider: sentry
organization: pulumiverse
major-version: 0
providerDefaultBranch: main
upstreamProviderOrg: jianyuan
publishRegistry: false
enableAutoRelease: false
plugins:
  - name: terraform
    version: "1.0.19"
    kind: converter
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
# license:
#   ignore:
toolVersions:
  go: "1.22.x"
pulumiConvert: 1
