// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry
{
    public static class GetSentryProject
    {
        /// <summary>
        /// Return a list of projects available to the authenticated session.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sentry = Pulumi.Sentry;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Sentry.GetSentryProject.Invoke(new()
        ///     {
        ///         Organization = "my-organization",
        ///         Slug = "my-project",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSentryProjectResult> InvokeAsync(GetSentryProjectArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSentryProjectResult>("sentry:index/getSentryProject:getSentryProject", args ?? new GetSentryProjectArgs(), options.WithDefaults());

        /// <summary>
        /// Return a list of projects available to the authenticated session.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Sentry = Pulumi.Sentry;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Sentry.GetSentryProject.Invoke(new()
        ///     {
        ///         Organization = "my-organization",
        ///         Slug = "my-project",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSentryProjectResult> Invoke(GetSentryProjectInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSentryProjectResult>("sentry:index/getSentryProject:getSentryProject", args ?? new GetSentryProjectInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSentryProjectArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The slug of the organization the resource belongs to.
        /// </summary>
        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        /// <summary>
        /// The slug of this project.
        /// </summary>
        [Input("slug", required: true)]
        public string Slug { get; set; } = null!;

        public GetSentryProjectArgs()
        {
        }
        public static new GetSentryProjectArgs Empty => new GetSentryProjectArgs();
    }

    public sealed class GetSentryProjectInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The slug of the organization the resource belongs to.
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        /// <summary>
        /// The slug of this project.
        /// </summary>
        [Input("slug", required: true)]
        public Input<string> Slug { get; set; } = null!;

        public GetSentryProjectInvokeArgs()
        {
        }
        public static new GetSentryProjectInvokeArgs Empty => new GetSentryProjectInvokeArgs();
    }


    [OutputType]
    public sealed class GetSentryProjectResult
    {
        /// <summary>
        /// The color of this project.
        /// </summary>
        public readonly string Color;
        /// <summary>
        /// The date this project was created.
        /// </summary>
        public readonly string DateCreated;
        /// <summary>
        /// The features of this project.
        /// </summary>
        public readonly ImmutableArray<string> Features;
        /// <summary>
        /// The slug of this project.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The internal ID of this project.
        /// </summary>
        public readonly string InternalId;
        /// <summary>
        /// Whether this project is public.
        /// </summary>
        public readonly bool IsPublic;
        /// <summary>
        /// The name of this project.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The slug of the organization the resource belongs to.
        /// </summary>
        public readonly string Organization;
        /// <summary>
        /// The platform of this project.
        /// </summary>
        public readonly string Platform;
        /// <summary>
        /// The slug of this project.
        /// </summary>
        public readonly string Slug;

        [OutputConstructor]
        private GetSentryProjectResult(
            string color,

            string dateCreated,

            ImmutableArray<string> features,

            string id,

            string internalId,

            bool isPublic,

            string name,

            string organization,

            string platform,

            string slug)
        {
            Color = color;
            DateCreated = dateCreated;
            Features = features;
            Id = id;
            InternalId = internalId;
            IsPublic = isPublic;
            Name = name;
            Organization = organization;
            Platform = platform;
            Slug = slug;
        }
    }
}
