// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry
{
    public static class GetSentryMetricAlert
    {
        public static Task<GetSentryMetricAlertResult> InvokeAsync(GetSentryMetricAlertArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSentryMetricAlertResult>("sentry:index/getSentryMetricAlert:getSentryMetricAlert", args ?? new GetSentryMetricAlertArgs(), options.WithDefaults());

        public static Output<GetSentryMetricAlertResult> Invoke(GetSentryMetricAlertInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSentryMetricAlertResult>("sentry:index/getSentryMetricAlert:getSentryMetricAlert", args ?? new GetSentryMetricAlertInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSentryMetricAlertArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The internal ID for this metric alert.
        /// </summary>
        [Input("internalId", required: true)]
        public string InternalId { get; set; } = null!;

        /// <summary>
        /// The slug of the organization the metric alert belongs to.
        /// </summary>
        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        /// <summary>
        /// The slug of the project the metric alert belongs to.
        /// </summary>
        [Input("project", required: true)]
        public string Project { get; set; } = null!;

        public GetSentryMetricAlertArgs()
        {
        }
        public static new GetSentryMetricAlertArgs Empty => new GetSentryMetricAlertArgs();
    }

    public sealed class GetSentryMetricAlertInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The internal ID for this metric alert.
        /// </summary>
        [Input("internalId", required: true)]
        public Input<string> InternalId { get; set; } = null!;

        /// <summary>
        /// The slug of the organization the metric alert belongs to.
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        /// <summary>
        /// The slug of the project the metric alert belongs to.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public GetSentryMetricAlertInvokeArgs()
        {
        }
        public static new GetSentryMetricAlertInvokeArgs Empty => new GetSentryMetricAlertInvokeArgs();
    }


    [OutputType]
    public sealed class GetSentryMetricAlertResult
    {
        public readonly string Aggregate;
        public readonly string Dataset;
        public readonly string Environment;
        /// <summary>
        /// The events type of dataset.
        /// </summary>
        public readonly ImmutableArray<string> EventTypes;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The internal ID for this metric alert.
        /// </summary>
        public readonly string InternalId;
        /// <summary>
        /// The metric alert name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The slug of the organization the metric alert belongs to.
        /// </summary>
        public readonly string Organization;
        public readonly string Owner;
        /// <summary>
        /// The slug of the project the metric alert belongs to.
        /// </summary>
        public readonly string Project;
        public readonly string Query;
        public readonly double ResolveThreshold;
        public readonly int ThresholdType;
        public readonly double TimeWindow;
        public readonly ImmutableArray<Outputs.GetSentryMetricAlertTriggerResult> Triggers;

        [OutputConstructor]
        private GetSentryMetricAlertResult(
            string aggregate,

            string dataset,

            string environment,

            ImmutableArray<string> eventTypes,

            string id,

            string internalId,

            string name,

            string organization,

            string owner,

            string project,

            string query,

            double resolveThreshold,

            int thresholdType,

            double timeWindow,

            ImmutableArray<Outputs.GetSentryMetricAlertTriggerResult> triggers)
        {
            Aggregate = aggregate;
            Dataset = dataset;
            Environment = environment;
            EventTypes = eventTypes;
            Id = id;
            InternalId = internalId;
            Name = name;
            Organization = organization;
            Owner = owner;
            Project = project;
            Query = query;
            ResolveThreshold = resolveThreshold;
            ThresholdType = thresholdType;
            TimeWindow = timeWindow;
            Triggers = triggers;
        }
    }
}
