// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Outputs
{

    [OutputType]
    public sealed class GetSentryDashboardWidgetResult
    {
        public readonly string DisplayType;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        public readonly string Interval;
        public readonly ImmutableArray<Outputs.GetSentryDashboardWidgetLayoutResult> Layouts;
        public readonly int Limit;
        public readonly ImmutableArray<Outputs.GetSentryDashboardWidgetQueryResult> Queries;
        /// <summary>
        /// Dashboard title.
        /// </summary>
        public readonly string Title;
        public readonly string WidgetType;

        [OutputConstructor]
        private GetSentryDashboardWidgetResult(
            string displayType,

            string id,

            string interval,

            ImmutableArray<Outputs.GetSentryDashboardWidgetLayoutResult> layouts,

            int limit,

            ImmutableArray<Outputs.GetSentryDashboardWidgetQueryResult> queries,

            string title,

            string widgetType)
        {
            DisplayType = displayType;
            Id = id;
            Interval = interval;
            Layouts = layouts;
            Limit = limit;
            Queries = queries;
            Title = title;
            WidgetType = widgetType;
        }
    }
}
