// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/pulumiverse/pulumi-sentry/sdk/go/sentry/internal"
)

var _ = internal.GetEnvOrDefault

// The target Sentry Base API URL in the format `https://[hostname]/api/`. The default value is `https://sentry.io/api/`.
// The value must be provided when working with Sentry On-Premise. The value can be sourced from the `SENTRY_BASE_URL`
// environment variable.
func GetBaseUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "sentry:baseUrl")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "SENTRY_BASE_URL"); d != nil {
		value = d.(string)
	}
	return value
}

// The authentication token used to connect to Sentry. The value can be sourced from the `SENTRY_AUTH_TOKEN` environment
// variable.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "sentry:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "SENTRY_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}
