// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Sentry Metric Alert resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sentry from "@pulumi/sentry";
 * import * as sentry from "@pulumiverse/sentry";
 *
 * const slack = sentry.getSentryOrganizationIntegration({
 *     organization: mainSentryProject.organization,
 *     providerKey: "slack",
 *     name: "Slack Workspace",
 * });
 * const main = new sentry.SentryMetricAlert("main", {
 *     organization: mainSentryProject.organization,
 *     project: mainSentryProject.id,
 *     name: "My metric alert",
 *     dataset: "events",
 *     query: "",
 *     aggregate: "count()",
 *     timeWindow: 60,
 *     thresholdType: 0,
 *     resolveThreshold: 0,
 *     triggers: [
 *         {
 *             actions: [{
 *                 type: "email",
 *                 targetType: "team",
 *                 targetIdentifier: mainSentryTeam.teamId,
 *             }],
 *             alertThreshold: 300,
 *             label: "critical",
 *             thresholdType: 0,
 *         },
 *         {
 *             actions: [{
 *                 type: "slack",
 *                 targetType: "specific",
 *                 targetIdentifier: "#slack-channel",
 *                 integrationId: slack.then(slack => slack.id),
 *             }],
 *             alertThreshold: 300,
 *             label: "critical",
 *             thresholdType: 0,
 *         },
 *         {
 *             alertThreshold: 100,
 *             label: "warning",
 *             thresholdType: 0,
 *         },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * import using the organization, project slugs and rule id from the URL:
 *
 * https://sentry.io/organizations/[org-slug]/projects/[project-slug]/
 *
 * https://sentry.io/organizations/[org-slug]/alerts/rules/details/[rule-id]/
 *
 * or
 *
 * https://sentry.io/organizations/[org-slug]/alerts/metric-rules/[project-slug]/[rule-id]/
 *
 * ```sh
 * $ pulumi import sentry:index/sentryMetricAlert:SentryMetricAlert default org-slug/project-slug/rule-id
 * ```
 */
export class SentryMetricAlert extends pulumi.CustomResource {
    /**
     * Get an existing SentryMetricAlert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SentryMetricAlertState, opts?: pulumi.CustomResourceOptions): SentryMetricAlert {
        return new SentryMetricAlert(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sentry:index/sentryMetricAlert:SentryMetricAlert';

    /**
     * Returns true if the given object is an instance of SentryMetricAlert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SentryMetricAlert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SentryMetricAlert.__pulumiType;
    }

    /**
     * The aggregation criteria to apply
     */
    public readonly aggregate!: pulumi.Output<string>;
    /**
     * The Sentry Alert category
     */
    public readonly dataset!: pulumi.Output<string | undefined>;
    /**
     * Perform Alert rule in a specific environment
     */
    public readonly environment!: pulumi.Output<string>;
    /**
     * The events type of dataset.
     */
    public readonly eventTypes!: pulumi.Output<string[] | undefined>;
    /**
     * The internal ID for this metric alert.
     */
    public /*out*/ readonly internalId!: pulumi.Output<string>;
    /**
     * The metric alert name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The slug of the organization the metric alert belongs to.
     */
    public readonly organization!: pulumi.Output<string>;
    /**
     * Specifies the owner id of this Alert rule
     */
    public readonly owner!: pulumi.Output<string>;
    /**
     * The slug of the project to create the metric alert for.
     */
    public readonly project!: pulumi.Output<string>;
    /**
     * The query filter to apply
     */
    public readonly query!: pulumi.Output<string>;
    /**
     * The value at which the Alert rule resolves
     */
    public readonly resolveThreshold!: pulumi.Output<number | undefined>;
    /**
     * The type of threshold
     */
    public readonly thresholdType!: pulumi.Output<number>;
    /**
     * The period to evaluate the Alert rule in minutes
     */
    public readonly timeWindow!: pulumi.Output<number>;
    public readonly triggers!: pulumi.Output<outputs.SentryMetricAlertTrigger[]>;

    /**
     * Create a SentryMetricAlert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SentryMetricAlertArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SentryMetricAlertArgs | SentryMetricAlertState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SentryMetricAlertState | undefined;
            resourceInputs["aggregate"] = state ? state.aggregate : undefined;
            resourceInputs["dataset"] = state ? state.dataset : undefined;
            resourceInputs["environment"] = state ? state.environment : undefined;
            resourceInputs["eventTypes"] = state ? state.eventTypes : undefined;
            resourceInputs["internalId"] = state ? state.internalId : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["organization"] = state ? state.organization : undefined;
            resourceInputs["owner"] = state ? state.owner : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["query"] = state ? state.query : undefined;
            resourceInputs["resolveThreshold"] = state ? state.resolveThreshold : undefined;
            resourceInputs["thresholdType"] = state ? state.thresholdType : undefined;
            resourceInputs["timeWindow"] = state ? state.timeWindow : undefined;
            resourceInputs["triggers"] = state ? state.triggers : undefined;
        } else {
            const args = argsOrState as SentryMetricAlertArgs | undefined;
            if ((!args || args.aggregate === undefined) && !opts.urn) {
                throw new Error("Missing required property 'aggregate'");
            }
            if ((!args || args.organization === undefined) && !opts.urn) {
                throw new Error("Missing required property 'organization'");
            }
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if ((!args || args.query === undefined) && !opts.urn) {
                throw new Error("Missing required property 'query'");
            }
            if ((!args || args.thresholdType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'thresholdType'");
            }
            if ((!args || args.timeWindow === undefined) && !opts.urn) {
                throw new Error("Missing required property 'timeWindow'");
            }
            if ((!args || args.triggers === undefined) && !opts.urn) {
                throw new Error("Missing required property 'triggers'");
            }
            resourceInputs["aggregate"] = args ? args.aggregate : undefined;
            resourceInputs["dataset"] = args ? args.dataset : undefined;
            resourceInputs["environment"] = args ? args.environment : undefined;
            resourceInputs["eventTypes"] = args ? args.eventTypes : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["organization"] = args ? args.organization : undefined;
            resourceInputs["owner"] = args ? args.owner : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["query"] = args ? args.query : undefined;
            resourceInputs["resolveThreshold"] = args ? args.resolveThreshold : undefined;
            resourceInputs["thresholdType"] = args ? args.thresholdType : undefined;
            resourceInputs["timeWindow"] = args ? args.timeWindow : undefined;
            resourceInputs["triggers"] = args ? args.triggers : undefined;
            resourceInputs["internalId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SentryMetricAlert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SentryMetricAlert resources.
 */
export interface SentryMetricAlertState {
    /**
     * The aggregation criteria to apply
     */
    aggregate?: pulumi.Input<string>;
    /**
     * The Sentry Alert category
     */
    dataset?: pulumi.Input<string>;
    /**
     * Perform Alert rule in a specific environment
     */
    environment?: pulumi.Input<string>;
    /**
     * The events type of dataset.
     */
    eventTypes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The internal ID for this metric alert.
     */
    internalId?: pulumi.Input<string>;
    /**
     * The metric alert name.
     */
    name?: pulumi.Input<string>;
    /**
     * The slug of the organization the metric alert belongs to.
     */
    organization?: pulumi.Input<string>;
    /**
     * Specifies the owner id of this Alert rule
     */
    owner?: pulumi.Input<string>;
    /**
     * The slug of the project to create the metric alert for.
     */
    project?: pulumi.Input<string>;
    /**
     * The query filter to apply
     */
    query?: pulumi.Input<string>;
    /**
     * The value at which the Alert rule resolves
     */
    resolveThreshold?: pulumi.Input<number>;
    /**
     * The type of threshold
     */
    thresholdType?: pulumi.Input<number>;
    /**
     * The period to evaluate the Alert rule in minutes
     */
    timeWindow?: pulumi.Input<number>;
    triggers?: pulumi.Input<pulumi.Input<inputs.SentryMetricAlertTrigger>[]>;
}

/**
 * The set of arguments for constructing a SentryMetricAlert resource.
 */
export interface SentryMetricAlertArgs {
    /**
     * The aggregation criteria to apply
     */
    aggregate: pulumi.Input<string>;
    /**
     * The Sentry Alert category
     */
    dataset?: pulumi.Input<string>;
    /**
     * Perform Alert rule in a specific environment
     */
    environment?: pulumi.Input<string>;
    /**
     * The events type of dataset.
     */
    eventTypes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The metric alert name.
     */
    name?: pulumi.Input<string>;
    /**
     * The slug of the organization the metric alert belongs to.
     */
    organization: pulumi.Input<string>;
    /**
     * Specifies the owner id of this Alert rule
     */
    owner?: pulumi.Input<string>;
    /**
     * The slug of the project to create the metric alert for.
     */
    project: pulumi.Input<string>;
    /**
     * The query filter to apply
     */
    query: pulumi.Input<string>;
    /**
     * The value at which the Alert rule resolves
     */
    resolveThreshold?: pulumi.Input<number>;
    /**
     * The type of threshold
     */
    thresholdType: pulumi.Input<number>;
    /**
     * The period to evaluate the Alert rule in minutes
     */
    timeWindow: pulumi.Input<number>;
    triggers: pulumi.Input<pulumi.Input<inputs.SentryMetricAlertTrigger>[]>;
}
